### ISSUE TITLE
what is the NotesFor.HtmlToOpenXml reference, where is source code of it.

### ISSUE THREAD

**Issue by cmf41013** [zaagan/Docx-Html-Docx#2]
the code:
HtmlConverter converter = new HtmlConverter(mainPart);
using NotesFor.HtmlToOpenXml ;
which use file HtmlToOpenXml.dll, where source code it it? thanks

**Comment by zaagan** [comment]
Hello Buddy,
The source code can be found here :
**[HTML To Open XML](https://github.com/onizet/html2openxml)**
